= Groovy Workshop image:https://travis-ci.org/mkutz/groovy-workshop.svg?branch=master["Build Status", link="https://travis-ci.org/mkutz/groovy-workshop"]
Michael Kutz <mail@assertagile.de>
v0.1, 2019-04-05
:toc:
:experimental:
:icons: font
:source-highlighter: coderay
:homepage: https://github.com/mkutz/groovy-workshop
:url-groovy-homepage: http://www.groovy-lang.org/
:url-gradle-homepage: https://gradle.org/
:url-maven-homepage: https://maven.apache.org/
:url-groovy-docs-maven-integration: http://docs.groovy-lang.org/latest/html/documentation/tools-groovyc.html#_maven_integration
:url-groovy-differences: http://groovy-lang.org/differences.html
:url-groovy-style-guide: http://groovy-lang.org/style-guide.html
:path-person-java-class: src/main/java/de/assertagile/workshop/groovy/Person.java
:path-person-groovy-class: src/main/groovy/de/assertagile/workshop/groovy/Person.groovy
:path-person-service-java-class: src/main/java/de/assertagile/workshop/groovy/PersonService.java
:path-person-service-groovy-class: src/main/groovy/de/assertagile/workshop/groovy/PersonService.groovy
:path-person-java-test: src/test/java/de/assertagile/workshop/groovy/PersonTest.java
:path-person-groovy-test: src/test/groovy/de/assertagile/workshop/groovy/PersonTest.groovy
:path-person-service-java-test: src/test/java/de/assertagile/workshop/groovy/PersonServiceTest.java
:path-person-service-groovy-test: src/test/groovy/de/assertagile/workshop/groovy/PersonServiceTest.groovy
:url-groovy-transform-package-doc: http://docs.groovy-lang.org/latest/html/gapi/groovy/transform/package-summary.html
:url-groovy-testing: http://groovy-lang.org/testing.html
:url-groovy-json: http://groovy-lang.org/json.html
:url-groovy-dsls: http://groovy-lang.org/dsls.html

Workshop for {url-groovy-homepage}[Groovy] programming language with a special focus on Java(TM) developers.

== Setup

This workshop uses {url-gradle-homepage}[Gradle] as its build tool.
Generally it is also possible to run Groovy via {url-maven-homepage}[Maven] (see {url-groovy-docs-maven-integration}[Groovy docs on Maven integration]) but {url-gradle-homepage}[Gradle]'s support for different source sets -- e.g. one for Groovy and Java -- is very useful for this workshop.

== Part 1: Syntax Differences to Java

In this part we'll try to convert a Plain Old Java Object (POJO) into a Plain Old Groovy Object (POGO) to find the most basic differences between Java and Groovy.

All answers you might be looking for can be found in the {url-groovy-differences}[Differences with Java] (and the {url-groovy-style-guide}[Groovy Style Guide]).

- [x] Take a look at the project, especially at link:{path-person-java-class}[`Person` Java class]. Try to run the tests:
+
[source,bash]
----
./gradlew test
----
- [x] Let's turn the link:{path-person-java-class}[`Person` Java class] into a Groovy class. Just move it from `src/main/java` to `src/main/groovy` and change the filename extension from `.java` to `.groovy`
+
[source,bash,subs=attributes]
----
mv {path-person-java-class} \
   {path-person-groovy-class}
----
+
Run the tests again, understand & fix the error.
You might want to read the {url-groovy-differences}#_behaviour_of_code_code[Behaviour of `==`] again.
// equals and `==`
- [ ] Keeping the {url-groovy-differences}[Differences with Java] in mind, make the link:{path-person-groovy-class} as Groovy as you can.
Run the tests after each change.
+
Hint: my solution has only 50 lines of code (keeping white space as is)
+
NOTE: There is a IntelliJ action (kbd:[Ctrl+Shift+A]) called "cleanup code".
+
// optional `;`
// `public` by default
// property fields
// optional `return` -> isOfAge
// string interpolation -> toString
// optional parameter typing -> equals
// default parameter values (constructor)

== Part 2: More Differences

- [ ] Now let's move something with more logic over. Turn link:{path-person-service-java-class}[`PersonService`] into a Groovy class.
+
[source,bash,subs=attributes]
----
mv {path-person-service-java-class} \
   {path-person-service-groovy-class}
----
+
Try to compile.
Fix the compile errors and run the tests.
+
You might want to look at the section about {url-groovy-differences}#_lambdas[Lambdas].
// lambdas & colures
- [ ] Again try to make link:{path-person-service-groovy-class}[`PersonService` Groovy class] truly Groovy.
// list sytax
// find & findAll

== Part 3: Groovy Testing (Basics)

Now we are going to convert our tests over to the Groovy side.

- [ ] Let's just move the link:{path-person-java-test}[`PersonTest` Java test] first as we did with the classes before:
+
[source,bash,subs=attributes]
----
mv {path-person-java-test} \
   {path-person-groovy-test}
----
+
Run it and make it Groovy.
// JUnit 5 + Groovy
// alias import (optional)
- [ ] Now also move link:{path-person-service-java-test}[`PersonServiceTest` Java test]:
[source,bash,subs=attributes]
+
----
mv src/test/java/de/assertagile/workshop/groovy/PersonServiceTest.java \
   src/test/groovy/de/assertagile/workshop/groovy/PersonServiceTest.groovy
----
+
There will be a compile error.
Maybe you can find a creative way to fix that without using a `\` in the {url-groovy-style-guide}[Groovy Style Guide].
// slashy strings
// Groovy regex
- [ ] The output of the assertion errors in our tests is quite useless.
Let's replace the assertions with {url-groovy-testing}#_power_assertions[Power Assertions] and the {url-groovy-testing}#_junit_4(`GroovyAssert` util).
+
Actually the Power Assertions won't help with the current failures. Try to break a test intentionally to see the "Power". E.g. remove one `Person` in the second test's assertion.
// power assertions
// GroovyAssert
- [ ] Try to fix the remaining tests.
You might find {url-groovy-differences}#_multi_methods[the paragraph about Multi-methods] pretty useful here.
// runtime method selection
- [ ] Make the test truly Groovy.
// collection literals
- [ ] Change the various service initializations to use the {url-groovy-style-guide}#_initializing_beans_with_named_parameters_and_the_default_constructor[named parameters constructor].
// named parameters constructor

== Part 4: Let's get Groovy

In this part we add some more Groovy power to the existing classes and tests.

- [ ] That `hashCode` and `equals` implementation are noisy and easily forgotten to be adjusted.
Let's play with annotations from the {url-groovy-transform-package-doc}[`groovy.transform` package].
// transform toString & hashCode
- [ ] The email address should be read-only, too.
See if you find an even better annotation now.
// immutable => map constructor
- [ ] Read {url-groovy-json}[Parsing and producing JSON] and extend the link:{path-person-groovy-class}[`Person` Groovy class] with a `toJson` method which returns the properties in pretty printed JSON.
Don't forget to extend link:{path-person-groovy-test}[`PersonTest`] (first).
// JSONOutput, JSONSlurper
- [ ] ...

== Part 5: Domain Specific Languages (Outlook)

This part is about how to create {url-groovy-dsls}[domain specific languages with Groovy].
This is less formal then you might think.
Files will still be `.groovy` files, you will still compile them the same way and your IDE will still understand, what you are doing.

- [ ] Replace the `addAll` method with the `<<<` operator, so the following test succeeds:
+
[source,groovy]
----
service <<< [TODD, ANDREA]
assert service.persons == [TODD, ANDREA]
----
- [ ] Change the predicate variant of `findPersons`, so the following test works:
+
[source,groovy]
----
assert service.findPersons { name == "Todd Ler" } == TODD
----
+
Hint: The {url-groovy-dsls}#section-delegatesto[`@DelegatesTo` annotation] might help.
